### PR TITLE
Adds specs for time

### PR DESCRIPTION
**Pull request by gampleman**
I’ve added 14 specs for time recurrence. There’s probably more combinations that could be thought of, but this should be enough to get started.

### CODE REVIEW

**Comment by yb66** [comment]
Thanks for this. I'll just finish what I'm doing and review it. Did you try the develop branch with your app? I'd be interested to know if it picks up any errors, as I'm considering releasing the changes as a release candidate (instead of letting it sit there while I worry about breaking other people's stuff!)

iain

**Comment by gampleman** [comment]
Yeah, I got an error (which I forgot to report, sorry) which seems to be caused by ActiveSupport adding `to_time` to `String`, which triggers this code path: https://github.com/yb66/tickle/blob/develop/lib/tickle.rb#L32 (which probably isn't tested, as `tickled` is undefined at that point). I would probably fix it something like this:

``` ruby
def self.parse(asked, options = {})
    asked = asked.to_s if asked.respond_to? :to_time

    tickled = Tickled.new asked, options
    _parse tickled
 end
```

**Comment by yb66** [comment]
Ok, thanks. I’ll sort that out later too.

Really appreciate it.

iain

**Comment by yb66** [comment]
I believe I've fixed the Active Support error. The specs look fine, I'll re-aquaint myself with the codebase and try and add those features.

iain

**Pull request merged**
