### PR TITLE
Remove the references to Numerizer and better time handling

### PR DESCRIPTION
**Pull request by bjonord**
```
~/.rvm/gems/ruby-2.3.3@ticketsolve/gems/tickle-1.0.2/lib/numerizer/numerizer.rb:5: warning: already initialized constant Numerizer::DIRECT_NUMS
~/.rvm/gems/ruby-2.3.3@ticketsolve/gems/chronic-0.2.3/lib/numerizer/numerizer.rb:5: warning: previous definition of DIRECT_NUMS was here
~/.rvm/gems/ruby-2.3.3@ticketsolve/gems/tickle-1.0.2/lib/numerizer/numerizer.rb:30: warning: already initialized constant Numerizer::TEN_PREFIXES
~/.rvm/gems/ruby-2.3.3@ticketsolve/gems/chronic-0.2.3/lib/numerizer/numerizer.rb:30: warning: previous definition of TEN_PREFIXES was here
~/.rvm/gems/ruby-2.3.3@ticketsolve/gems/tickle-1.0.2/lib/numerizer/numerizer.rb:40: warning: already initialized constant Numerizer::BIG_PREFIXES
~/.rvm/gems/ruby-2.3.3@ticketsolve/gems/chronic-0.2.3/lib/numerizer/numerizer.rb:40: warning: previous definition of BIG_PREFIXES was here
```

To silence these warnings the extra reference to the `numerizer` needs to be removed. This was done in Tickle as Chronic defines its own version.

Also the parsing of dates and time when the bump is used blows up for odd numbers. For example adding 10 to 22 in the month of February makes Date or Time blow up the way it is done today. 

`Date.civil(self.year, self.month, self.day + amount)` When `amount` is > 9 and `self.day` is 22.

### CODE REVIEW

**Comment by bjonord** [comment]
Not sure how to open a PR against a tag.

**Comment by yb66** [comment]
Hi

Neither do I, but I'll just pull in directly using git rather than use this interface anyway. Is this against the latest version?

Regards,
iain

**Comment by bjonord** [comment]
Hi @yb66 
It is against tag v1.0.2. 

We aren't using the RC yet. Will probably start contributing to it though as we will be using this gem for the forseeable future. 😄

**Comment by yb66** [comment]
That's fantastic news. I'll take a look this afternoon.

iain

**Comment by bjonord** [comment]
Cheers for the fast response!

**Comment by yb66** [comment]
You were just lucky and caught me mid-dawdle :)

I've merged in the changes and made a couple of minor ones myself as some other things broke. Nothing to worry about but check out https://github.com/yb66/tickle/tree/remove-numerizer-dup and let me know it works for you too and I'll tag it as v1.1.0.

I'll release a gem for it too, unless you want to just use the branch?

iain

**Comment by bjonord** [comment]
👍 
Looks good! 

As far as releasing a gem, for the sake of our code, no need to release it, but perhaps other people out there could benefit. Not sure! 😄

**Comment by yb66** [comment]
Nice one. I've pushed the tag and a new gem. Why not! :)

iain

**Pull request closed without merging**
